---
title: "2025 Sampling Locations"
author: "John Phelan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = F, warning = F, message = F)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(sf)
library(bcdata)
library(bcmaps)
library(readxl)
library(leaflet)
library(leafpop)
library(leaflet.extras)
library(janitor)
library(here)
library(openxlsx)
library(htmlwidgets)

knitr::opts_knit$set(root.dir = here::here(".."))

lan_root = "//SFP.IDIR.BCGOV/S140/S40203/WFC AEB/General/2 SCIENCE - Invasives/AIS_R_Projects/CMadsen_Wdrive/shared_data_sets/"


onedrive_wd = "//SFP.IDIR.BCGOV/S140/S40203/WFC AEB/General/2 SCIENCE - Invasives/AIS_R_Projects/LargeDataFiles/"

dat<-openxlsx::read.xlsx(here::here("./data/BC Veliger Sampling Inventory 2025_FINAL_REPORT.xlsx"))

dat_edna = read.csv(here::here("./data/2025_sample_locations_final.csv")) |> 
  filter(sample_type == "eDNA")

pylet_locations<- read_excel("Z:/2 SCIENCE - Invasives/GENERAL/Budget/Canada Nature fund 2023-2026/Year 2 (2025-2026)/eDNA ZQM Pylet Lab/Sample collection & results/ZQM data Batch 1 complete.xlsx",
                             sheet = "COS")

pylet_locations = pylet_locations |> 
  mutate(Lat = str_remove(Lat, " N"), Long = str_remove(Long, " W")) |> 
  mutate(Long = as.numeric(Long),
                       Lat = as.numeric(Lat)) |> 
  mutate(Long = -1*abs(Long)) |> 
  filter(!is.na(Long) & !is.na(Lat) & !is.na(Lake))

pylet_locations_sf <- st_as_sf(
  pylet_locations,
  coords = c("Long", "Lat"),
  crs = 4326,        # WGS84
  remove = FALSE    # keep Lon/Lat columns if you want
  
  
)


```


```{r data grab}

dat <- dat |> 
  clean_names()

dat<- dat |> 
  rename(count =  x1)

dat<- dat |> 
  mutate(date_collected_yyyy_mm_dd = as.Date(as.numeric(date_collected_yyyy_mm_dd), origin = "1899-01-01"))

dat_complete<-dat |> 
  mutate(long_decimal_degrees = as.numeric(long_decimal_degrees),
         lat_decimal_degrees = as.numeric(lat_decimal_degrees)) |> 
  filter(!is.na(lat_decimal_degrees) | !is.na(long_decimal_degrees))
dat_missing<-dat |> 
  mutate(long_decimal_degrees = as.numeric(long_decimal_degrees),
         lat_decimal_degrees = as.numeric(lat_decimal_degrees)) |> 
  filter(is.na(lat_decimal_degrees) | is.na(long_decimal_degrees))


#fix wrong longs - all should be negative
dat_complete<-dat_complete |> 
  mutate(long_decimal_degrees = ifelse(long_decimal_degrees > 0, long_decimal_degrees * -1, long_decimal_degrees))


dat_sf<-st_as_sf(dat_complete, coords = c("long_decimal_degrees", "lat_decimal_degrees"), crs = 4326)


############## 
# --------- we also want the eDNA samples taken in 2025
dat_edna = dat_edna |> 
  rename(count = X) |> 
  mutate(long_decimal_degrees = ifelse(long_decimal_degrees > 0, long_decimal_degrees * -1, long_decimal_degrees))
dat_edna_sf = st_as_sf(dat_edna, coords = c("long_decimal_degrees", "lat_decimal_degrees"), crs = 4326)

dfo_sar = sf::read_sf(paste0(onedrive_wd,"CNF/dfo_sara_and_crit_hab_bulltrout_and_sockeye_data.gpkg")) |> sf::st_transform(4326)

species_list <- c("Rocky Mountain Ridged Mussel")

rmrm = dfo_sar |>
  filter(Common_Name_EN %in% species_list) |> 
  st_transform(4326)


named_wbs <- read_rds(
  here::here("../AIS_SAR_prioritization_model/data/named_lakes_and_rivers.rds")
)


named_wbs_overlap <- named_wbs %>%
  filter(lengths(st_intersects(geometry, rmrm)) > 0) |> 
  st_transform(3005) |> 
  st_buffer(5000) |> 
  st_transform(4326)
# 
# dat_sf
# dat_edna_sf

dat_sf_overlap = dat_sf |> 
  filter(lengths(st_intersects(geometry, named_wbs_overlap)) > 0)

dat_edna_sf_overlap = dat_edna_sf |> 
  filter(lengths(st_intersects(geometry, named_wbs_overlap)) > 0)


pylet_overlap = pylet_locations_sf |> 
  filter(lengths(st_intersects(geometry, named_wbs_overlap)) > 0)

pylet_overlap_clean <- pylet_overlap |>
  rename(sample_name = matches("Sample Name")) |>
  mutate(sample_group = sample_name |>
           str_remove("\\s*-\\s*Batch\\s*\\d+") |>
           str_remove("\\s*#\\d+$")) |>
  filter(!str_detect(sample_group, regex("blank", ignore_case = TRUE))) |>
  select(-sample_group)



pylet_overlap_clean <- pylet_overlap_clean |>
  mutate(lat = st_coordinates(geometry)[, 2],
         lon = st_coordinates(geometry)[, 1])


```



```{r leaflet map, fig.width=10, fig.height=8}


sampling_levels <- unique(dat_sf$sampling_group_agency)

pal_sampling <- colorFactor(
  palette = c(
    "CLSS"   = "#66c2a5",
    "CSISS"  = "#fc8d62",
    "ONA"    = "#e78ac3",  # <-- pink (high contrast to water)
    "FVISS"  = "#a6d854",
    "MLWRS"  = "#ffd92f",
    "ISCBC"  = "#e5c494",
    "CKISS"  = "#b3b3b3",
    "EKISC"  = "#1b9e77",
    "BISS"   = "#d95f02",
    "OASISS" = "#7570b3",
    "ISCMV"  = "#66a61e",
    "MOE"    = "#e7298a"
  ),
  domain   = sampling_levels,
  na.color = "#cccccc"
)

pal_edna <- colorFactor(
  palette = "#3182bd",  # a distinct blue
  domain = dat_edna_sf$sample_type
)


leaflet() |> 
  addTiles(group = "OSM") |> 
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB") |> 
  addLayersControl(
    position = 'bottomleft',
    baseGroups = c("CartoDB", "OSM"),
    overlayGroups = c("Veliger Sampling", "eDNA Sampling"),
    options = layersControlOptions(collapsed = FALSE)
  ) |> 
  addPolygons(
    data = named_wbs_overlap,
    fillOpacity = 0.5,
    color = "grey",
    weight = 2
  ) |> 
  
  addCircleMarkers(
    data = dat_sf_overlap,
    group = "Veliger Sampling",
    color = ~pal_sampling(sampling_group_agency),
    fillOpacity = 0.8,
    radius = 2,
    label = ~paste0(waterbody, ", ", date_collected_yyyy_mm_dd),
    popup = leafpop::popupTable(
      dat_sf,
      zcol = c(
        "waterbody",
        "location_site_name",
        "date_collected_yyyy_mm_dd",
        "secchi_depth_m",
        "water_temperature_c",
        "p_h_in_water_column",
        "zebra_quagga_mussels_veligers",
        "sampling_group_agency"
      )
    )
  ) |> 
  addCircleMarkers(
    data = dat_edna_sf_overlap,
    group = "eDNA Sampling",
    color = "#3182bd",
    fillColor = "#3182bd",
    fillOpacity = 0.8,
    radius = 2,
    label = ~paste0(waterbody, ", ", date_collected),
    popup = leafpop::popupTable(
      dat_edna_sf,
      zcol = c(
        "waterbody",
        "location_site_name",
        "sampling_organisation",
        "date_collected",
        "sample_type"
      )
    )
  ) |> 
  addLegend(
    position = "bottomright",
    pal = pal_sampling,
    values = dat_sf$sampling_group_agency,
    title = "Sampling group / agency",
    opacity = 1,
    group = "Veliger Sampling"                # <-- ties legend to layer toggle
  ) |> 
  addLegend(
    position = "bottomright",
    colors = "#3182bd",
    labels = "eDNA Sampling",
    title = "eDNA",
    opacity = 1,
    group = "eDNA Sampling"                   # <-- ties legend to layer toggle
  ) |> 
  htmlwidgets::onRender("
    function(el, x) {
      var map = this;
      map.on('overlayadd overlayremove', function(e) {
        map.eachLayer(function(layer) {
          if (layer.options && layer.options.className) {
            var legendClass = layer.options.className;
            var groupName = e.name;
            if (legendClass.includes(groupName.replace(/ /g, '-'))) {
              layer.getElement().style.display = 
                e.type === 'overlayadd' ? 'block' : 'none';
            }
          }
        });
      });
    }
  ")



```


```{r save_locations}
# 
# dat_edna_sf_overlap
# 
# dat_sf_overlap

# write.csv(dat_sf_overlap, "./output/2025_veliger_sampling_rmrm.csv")
# write.csv(dat_edna_sf_overlap, "./output/2025_edna_sampling_rmrm.csv")
write.csv(pylet_overlap_clean, here::here("./output/2025_pylet_overlap_clean.csv"))
write.csv(pylet_locations_sf, here::here("./output/2025_pylet_all.csv"))

# 
# sampling_levels <- unique(dat_sf$sampling_group_agency)
# 
# pal_sampling <- c(
#   CLSS   = "#66c2a5",
#   CSISS  = "#fc8d62",
#   ONA    = "#e78ac3",
#   FVISS  = "#a6d854",
#   MLWRS  = "#ffd92f",
#   ISCBC  = "#e5c494",
#   CKISS  = "#b3b3b3",
#   EKISC  = "#1b9e77",
#   BISS   = "#d95f02",
#   OASISS = "#7570b3",
#   ISCMV  = "#66a61e",
#   MOE    = "#e7298a"
# )
# 
# dat_sf_overlap <- dat_sf_overlap %>%
#   mutate(
#     sampling_group_agency = as.character(sampling_group_agency)
#   )
# 
# 
# edna_color <- "#3182bd"
# 
#     buffered_bbox = sf::st_bbox(rmrm) |>
#       sf::st_as_sfc() |>
#       sf::st_as_sf() |>
#       sf::st_transform(3005) |>
#       sf::st_buffer(dist = 500)
# 
#      the_ocean_bm =  suppressMessages(suppressWarnings(basemaps::basemap_terra(ext = buffered_bbox,
#                                             map_service = "osm",
#                                             map_type = "streets")))
# 
# 
# ggplot() +
#   tidyterra::geom_spatraster_rgb(data = the_ocean_bm) +
#   # Veliger sampling points
#   geom_sf(
#     data = dat_sf_overlap,
#     aes(color = sampling_group_agency),
#     size = 1.8,
#     alpha = 0.8
#   ) +
# 
#   # eDNA sampling points
#   geom_sf(
#     data = dat_edna_sf_overlap,
#     color = edna_color,
#     size = 1.8,
#     alpha = 0.8
#   ) +
# 
#   # Color scales
#   scale_color_manual(
#     name   = "Sampling group / agency",
#     values = pal_sampling,
#     na.value = "#cccccc"
#   ) +
# 
#   # Map styling (CartoDB-like)
#   theme_minimal() +
#   theme(
#     panel.grid.major = element_blank(),
#     panel.grid.minor = element_blank(),
#     axis.title       = element_blank(),
#     legend.position  = "right"
#   ) +
# 
#   labs(
#     title = "Veliger and eDNA Sampling Locations",
#     subtitle = "Veliger sampling by agency; eDNA shown in blue"
#   )

```

