---
title: "Test"
author: "Chris Madsen"
date: "2023-04-17"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(
readxl,
ggpubr,
ggrepel,
ggExtra,
tidyverse,
leaflet,
sf,
RColorBrewer,
openxlsx,
scales,
lubridate,
tmap,
plotrix)

#=====================================================
#                       OPTIONS 
#=====================================================
my_opts = read_csv(paste0(str_extract(getwd(),".*ZQMussels[/]?"),"/Options.csv"))

#Which year should we focus on?
my.year = my_opts$year

#Update GIS maps? We probably want this turned on unless you are making fine adjustments to some figures.
update.gis = FALSE

#Are there any stations we would like to exclude from the excel-type figures?
#In 2021, we will exclude:
stations.to.include = c("Golden","Radium","Olsen","Yahk",
                        "Pacific","Osoyoos","Hwy 97c","Mt. Robson",
                        "Keremeos","Greenwood","Dawson Creek","Kaleden")

stations.to.put.aside = c("Scheduled Inspection","Boat Launch - Okanagan",
                          "Okanagan",
                          "Penticton Roving - Hwy 33", 
                          "Penticton Roving - Inspection Event")

# Just in case it's different, which stations do we want to show in the 
# leaflet maps?
leaflet.stations.to.include = c("Golden","Radium","Olsen","Dawson Creek","Mt. Robson","Penticton Roving","Keremeos","Osoyoos","Fraser Valley Roving","Pacific")

#Data folders
my.data.folder = paste0(my_opts$zqm_figure_local_folder,"data/")
my.external.data.folder = paste0(my_opts$remote_spatial_data,"Projects/ZQMussels/data/")

#Which folder should we put specific output files in?
my.output.folder = paste0(my_opts$zqm_figure_local_folder,"output/")
my.external.output.folder = paste0(my_opts$zqm_figure_output_remote_folder,my_opts$year)
zqm.operations.folder = my_opts$zqm_operations_data_folder
this.years.report.folder = paste0(my_opts$remote_spatial_data,"Projects/ZQMussels/",my.year," IMDP Final Report/")

#Where is the mussel-fouled tracking sheet?
MusselFouledTracker = paste0(my_opts$zqm_operations_data_folder,"Watercraft Inspection Data/", my.year," data/2022 mussel fouled boats tracking sheet.xlsx")

#What is the sheet name of the destination regions for the mussel fouled tracking sheet?
MF_tracker_sheet = "DestRegions"

#Where can we find the CBSA notifications excel sheet for this year?
if(file.exists(paste0(my.external.output.folder,"/GIS Maps and Excel Figures/",my.year," COS inbox notifications.xlsx"))){
  cbsa_dat = read_excel(paste0(my.external.output.folder,"/GIS Maps and Excel Figures/",my.year," COS inbox notifications.xlsx"),
                 sheet = "Filtered list")
}

#These lines below set options for all of the code for the rest of this script. You probably don't need to change any of these.
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.width = 8)
knitr::opts_chunk$set(fig.height = 4)
knitr::opts_knit$set(root.dir = paste0(my.external.output.folder,"/GIS Maps and Excel Figures/ExcelFigures"))

#Colour for some of the figures:
my.grey = "#5f6a6f"

#=====================================================
#                     END OF OPTIONS
#=====================================================

#If there is no folder for excel figures for the target year in the I: drive, make it now.
if(!dir.exists(paste0(my.external.output.folder,"/GIS Maps and Excel Figures/ExcelFigures"))){
  dir.create(paste0(my.external.output.folder,"/GIS Maps and Excel Figures/ExcelFigures/"))
}
```

```{r load in data}
setwd(my.data.folder)

dat = read.xlsx('figure_dat.xlsx') %>% 
  mutate(TimeOfInspection = convertToDateTime(TimeOfInspection)) %>% 
  as_tibble()

dat_all = read.xlsx('figure_dat_all.xlsx') %>%
  mutate(TimeOfInspection = openxlsx::convertToDateTime(TimeOfInspection)) %>% 
  as_tibble()

dat_hr = read.xlsx('figure_dat_hr.xlsx') %>% 
  mutate(TimeOfInspection = openxlsx::convertToDateTime(TimeOfInspection)) %>% 
  as_tibble()

dat_mf = read.xlsx('figure_dat_mf.xlsx') %>%
  mutate(TimeOfInspection = openxlsx::convertToDateTime(TimeOfInspection)) %>% 
  as_tibble()

flnro_lookup = read_excel(paste0(my.external.data.folder,"waterbody_name_flrno_region_lookup_table.xlsx")) %>% distinct()

abbrev = read_excel(paste0(my.external.data.folder,"Province_States_Abbreviation_Table.xlsx"))

#Lookup table for what the Previous Knowledge of AIS field's codes mean.
ais_know = read_excel(paste0(my.external.data.folder,"Previous_Knowledge_of_AIS_lookup_table.xlsx"))

# Outline of BC
bc_bound = bcmaps::bc_bound() %>% st_transform(crs = 4326)
```

```{r}
#Establish colour scheme for roving stations that we keep.
rovers = data.frame(Station = c("Hwy 97c","Keremeos","Greenwood","Kaleden","Fraser Valley Roving"),
                    StationType = "Roving")

station_types = bind_rows(rovers,
          data.frame(Station = dat %>% 
                       select(Station) %>% 
                       filter(!Station %in% rovers$Station) %>% 
                       distinct() %>% 
                       pull(Station),
                     StationType = "Permanent"))
rm(rovers)
```

```{r}
#Make one more vector of stations that we want to drop in the figures. These are roving stations.
rovers_to_drop = c("Scheduled Inspection","Other","Okanagan","Penticton Roving")
```

### Map 2

```{r map2_inspection_stations_by_type, fig.width=800}
# TEST # 
sources_centroid = sources_centroid %>% 
  mutate(jenks = list(BAMMtools::getJenksBreaks(HRInsp, k = 6))) %>% 
  unnest_wider(jenks, names_sep = '_') %>% 
  mutate(HRInsp_b = case_when(
    HRInsp <= jenks_2 ~ 1,
    HRInsp <= jenks_3 ~ 2,
    HRInsp <= jenks_4 ~ 3,
    HRInsp <= jenks_5 ~ 4,
    HRInsp <= jenks_6 ~ 5,
  )) %>%
  mutate(bin_label = case_when(
    HRInsp_b == 1 ~ paste0(jenks_1, ' - ', jenks_2),
    HRInsp_b == 2 ~ paste0(jenks_2+1, ' - ', jenks_3),
    HRInsp_b == 3 ~ paste0(jenks_3+1, ' - ', jenks_4),
    HRInsp_b == 4 ~ paste0(jenks_4+1, ' - ', jenks_5),
    HRInsp_b == 5 ~ paste0(jenks_5+1, ' - ', jenks_6)
  )) %>% 
  mutate(HRInsp_b = factor(HRInsp_b, levels = c(1:5))) %>% 
  arrange(HRInsp_b)

sources_centroid = st_set_geometry(sources_centroid, sources_centroid$geom)

# Remove rows for Mexican estados without inspections.
sources_centroid = sources_centroid %>% 
  filter(!(NAME_0 == 'Mexico' & is.na(HRInsp)))

# TEST #
source_pal = leaflet::colorFactor(
  palette = 'Spectral',
  domain = sources_centroid$HRInsp_b,
  reverse = T
)

labels = unique(sources_centroid$bin_label)

map_4 = leaflet() %>% 
  addProviderTiles(providers$CartoDB) %>%
  addCircleMarkers(
    color = 'black',
    weight = 1,
    fillOpacity = 0.8,
    fillColor = ~my_pal(HRInsp_b),
    # Apply HTML to the labels.
    label = ~lapply(paste0("<p style = 'font-size: large;color:",map_label_colour,"'>",ABBR,"</p>"), htmltools::HTML),
    labelOptions = labelOptions(noHide = T, textOnly = T,
                                textsize = 20),
    radius = ~as.numeric(HRInsp_b)*5,
    data = sources_centroid
  ) %>% 
  addLegend(
    pal = my_pal,
    values = ~HRInsp_b,
    title = "2022 Source of High Risk Inspections",
    labFormat = function(type, cuts, p) paste0(labels),
    data = sources_centroid
  ) %>% 
  addScaleBar('bottomleft',
              options = scaleBarOptions(maxWidth = 300)) %>% 
  setView(lat = 50, lng = -100, zoom = 4)

map_4
```

```{r trying_with_tmap!}
sources_centroid = read_sf(paste0(my_opts$remote_spatial_data,'Projects/ZQMussels/',my.year,' IMDP Final Report/data/spatial/Inspections_by_source_centroid.gpkg'))

# Add some labelling logic:
# 1. If a given state/province/estado has no inspections, its name should be grey.
#    and it should have no dot.
sources_centroid = sources_centroid %>% 
  mutate(map_label_colour = ifelse(is.na(HRInsp), 'grey', 'black'))

# TEST # 
sources_centroid = sources_centroid %>% 
  mutate(jenks = list(BAMMtools::getJenksBreaks(HRInsp, k = 6))) %>% 
  unnest_wider(jenks, names_sep = '_') %>% 
  mutate(HRInsp_b = case_when(
    HRInsp <= jenks_2 ~ 1,
    HRInsp <= jenks_3 ~ 2,
    HRInsp <= jenks_4 ~ 3,
    HRInsp <= jenks_5 ~ 4,
    HRInsp <= jenks_6 ~ 5,
  )) %>%
  mutate(bin_label = case_when(
    HRInsp_b == 1 ~ paste0(jenks_1, ' - ', jenks_2),
    HRInsp_b == 2 ~ paste0(jenks_2+1, ' - ', jenks_3),
    HRInsp_b == 3 ~ paste0(jenks_3+1, ' - ', jenks_4),
    HRInsp_b == 4 ~ paste0(jenks_4+1, ' - ', jenks_5),
    HRInsp_b == 5 ~ paste0(jenks_5+1, ' - ', jenks_6)
  )) %>% 
  # mutate(HRInsp_b = factor(HRInsp_b, levels = c(1:5))) %>% 
  arrange(HRInsp_b)

sources_centroid = st_set_geometry(sources_centroid, sources_centroid$geom)

# Remove rows for Mexican estados without inspections.
sources_centroid = sources_centroid %>% 
  filter(!(NAME_0 == 'Mexico' & is.na(HRInsp)))

# TEST #
source_pal = leaflet::colorFactor(
  palette = 'Spectral',
  domain = sources_centroid$HRInsp_b,
  reverse = T
)

northamerica_view = tibble(lon = c(-174,-50),
                           lat = c(73,11.2)) %>% 
  st_as_sf(coords = c("lon","lat"), crs = 4326)

# Download maptiles North America
northamerica_basemap = maptiles::get_tiles(x = northamerica_view, provider = 'CartoDB.Positron', zoom = 4, crop = F)

# Split the centroid spatial object into 2: one with high risk inspections,
# and one without.
centr_with_dat = sources_centroid %>% filter(!is.na(HRInsp))
centr_without_dat = sources_centroid %>% filter(is.na(HRInsp))

map_3_tmap = tm_shape(northamerica_basemap, bbox = northamerica_view) +
    tm_rgb() + 
  tm_add_legend(title = '2022 Home Residence\n Frequency',
                type = 'symbol',
                labels = unique(stations_sf$bin_label),
                col = my_pal(unique(stations_sf$num_insp_b)),
                size = log(unique(stations_sf$num_insp_b)+1)) + 
  tm_shape(centr_with_dat) + 
    tm_symbols(col = "HRInsp", 
               palette = '-Spectral',
               size = 'HRInsp_b',
               legend.col.show = FALSE,
               legend.size.show = FALSE,
               title.col = '') +
    tm_text("ABBR", auto.placement = T, 
            size = 0.75) +
  tm_shape(centr_without_dat) + 
    tm_text("ABBR", col = 'grey', 
            size = 0.8,
            auto.placement = FALSE) +
    tm_symbols(col = 'grey',
               size = 0.1) + 
  tm_scale_bar() + 
  tm_layout(legend.frame = 'black', 
            legend.position = c('left','bottom'),
            scale = 1.25)

tmap_save(tm = map_3_tmap, filename = 'map_3_tmap.jpg', dpi = 300)

```

